Repository rage/concepts, pull requests merged in 2019-10, with the labels that each got.

#345 Performance fixes
  .eslintrc
  backend/schema/datamodel.prisma
  backend/schema/extra.graphql
  backend/src/accessControl.js
  backend/src/resolvers/Mutation/Import.js
  backend/src/resolvers/Mutation/Merge.js
  backend/src/resolvers/Mutation/User.js
  backend/src/resolvers/Mutation/index.js
  backend/src/resolvers/Query/Concept.js
  backend/src/resolvers/Query/ConceptLink.js
  backend/src/resolvers/Query/Course.js
  backend/src/resolvers/Query/CourseLink.js
  backend/src/resolvers/Query/Export.js
  backend/src/resolvers/Query/Project.js
  backend/src/resolvers/Query/User.js
  backend/src/resolvers/Query/Workspace.js
  backend/src/resolvers/Query/index.js
  frontend/public/guide/entering-course-mapper.webm
  frontend/public/guide/home/create-workspace.webm
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/apollo/apolloClient.js
  frontend/src/apollo/update/concept.js
  frontend/src/apollo/update/conceptLink.js
  frontend/src/apollo/update/port.js
  frontend/src/components/InfoBox.js
  frontend/src/components/NavBar.js
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/tagSelectUtils.js
  frontend/src/dialogs/workspace/WorkspaceCreationActions.js
  frontend/src/graphql/Mutation/Authentication.js
  frontend/src/graphql/Mutation/ConceptLink.js
  frontend/src/graphql/Query/Course.js
  frontend/src/lib/eventMiddleware.js
  frontend/src/lib/generateName.js
  frontend/src/static/adjectives.json
  frontend/src/static/animals.json
  frontend/src/static/userGuide.json
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/join/JoinView.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/CourseContainer.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/MapperLinks.js
  frontend/src/views/mapper/PrerequisiteContainer.js
  frontend/src/views/mapper/concept/Concept.js
  frontend/src/views/mapper/concept/ConceptLink.js
  frontend/src/views/mapper/redirect/CreateCourseForm.js
  frontend/src/views/porting/PortView.js
  frontend/src/views/project/CloneView.js
Labels: internal

#349 More performance fixes
  frontend/src/App.js
  frontend/src/components/InfoBox.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseContainer.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/MapperLinks.js
Labels: internal, mapper view

#350 Don't join project multiple times
  frontend/src/views/join/JoinView.js
  frontend/src/views/project/CloneView.js
Labels: enhancement, internal, other ui

#351 Show existing workspace in join clone view
  frontend/src/views/login/LoginView.js
  frontend/src/views/project/CloneView.js
Labels: bug, other ui

#344 Add subscriptions to backend
  backend/prisma.yml
  backend/schema/extra.graphql
  backend/schema/generated/prisma-client/prisma.graphql
  backend/schema/generated/schema.graphql
  backend/src/errorLogger.js
  backend/src/index.js
  backend/src/middleware/authentication.js
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/ConceptLink.js
  backend/src/resolvers/Mutation/Course.js
  backend/src/resolvers/Mutation/CourseLink.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Subscription/Concept.js
  backend/src/resolvers/Subscription/ConceptLink.js
  backend/src/resolvers/Subscription/Course.js
  backend/src/resolvers/Subscription/CourseLink.js
  backend/src/resolvers/Subscription/Workspace.js
  backend/src/resolvers/Subscription/config/channels.js
  backend/src/resolvers/Subscription/config/index.js
  backend/src/resolvers/Subscription/config/pubsub.js
  backend/src/resolvers/Subscription/index.js
  frontend/src/setupProxy.js
Labels: backend, enhancement

#359 Add CORS headers to progress API
  backend/package.json
  backend/src/index.js
  backend/yarn.lock
  development.yml
Labels: backend

#360 Fix course links
  frontend/src/apollo/update/courseLink.js
  frontend/src/views/mapper/CourseTray.js
Labels: bug

#364 Miscellaneous refactoring
  backend/schema/generated/prisma-client/index.d.ts
  backend/schema/generated/prisma-client/prisma-schema.js
  frontend/public/index.html
  frontend/public/res/favicon.png
  frontend/public/res/googleInit.js
  frontend/public/res/index.css
  frontend/public/res/manifest.json
  frontend/src/App.js
  frontend/src/Wrapper.js
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/components/EditableTable.js
  frontend/src/components/InfoBox.js
  frontend/src/components/InfoSnackbar.js
  frontend/src/components/NavBar.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/DialogProvider.js
  frontend/src/dialogs/sharing/LinkSharingActions.js
  frontend/src/dialogs/workspace/WorkspaceCreationActions.js
  frontend/src/index.js
  frontend/src/lib/store/index.js
  frontend/src/lib/store/login.js
  frontend/src/lib/store/message.js
  frontend/src/lib/useRouter.js
  frontend/src/views/WindowTooSmall.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/home/HomeView.js
  frontend/src/views/home/ProjectList.js
  frontend/src/views/join/JoinView.js
  frontend/src/views/login/LoginView.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/WorkspaceManagementView.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/concept/Concept.js
  frontend/src/views/mapper/redirect/CreateCourseForm.js
  frontend/src/views/members/MembersView.js
  frontend/src/views/porting/PortView.js
  frontend/src/views/project/CloneView.js
  frontend/src/views/project/PointGroupsView.js
  frontend/src/views/project/ProjectView.js
  frontend/src/views/user/UserView.js
Labels: internal

#365 Fix dialog explosion
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/authentication/useLoginDialog.js
Labels: internal

#367 Make Haka login URL dynamic
  Dockerfile
  backend/schema/extra.graphql
  backend/schema/generated/schema.graphql
  backend/src/resolvers/Query/Authentication.js
  backend/src/saml/serviceProvider.js
  development.yml
  frontend/public/index.html
  frontend/public/res/googleInit.js
  frontend/src/graphql/Query/Authentication.js
  frontend/src/lib/authentication/google.js
  frontend/src/lib/authentication/haka.js
  frontend/src/lib/authentication/index.js
  frontend/src/lib/eventMiddleware.js
  frontend/src/views/login/LoginView.js
  frontend/src/views/user/UserView.js
  production.yml
Labels: internal

#373 Add support for collapsing courses
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseContainer.js
  frontend/src/views/mapper/MapperLinks.js
  frontend/src/views/mapper/PrerequisiteContainer.js
Labels: enhancement, mapper view

#375 Move edit and delete buttons into menu in manager
  frontend/src/components/InfoBox.js
  frontend/src/views/manager/ConceptList.js
  frontend/src/views/manager/ConceptListItem.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/CourseListItem.js
Labels: manager view

#376 Order courses and concepts in mapper view
  frontend/src/graphql/Mutation/CourseLink.js
  frontend/src/views/manager/ConceptList.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/ordering.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseContainer.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/PrerequisiteContainer.js
Labels: mapper view

#378 Add sentry error monitoring
  frontend/package.json
  frontend/src/index.js
  frontend/yarn.lock
Labels: internal

#381 Fix hidden dialog fields not being included in mutation data
  frontend/src/dialogs/Dialog.js
Labels: bug, internal

#383 Store manager view open course in url
  frontend/src/App.js
  frontend/src/components/NavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/views/manager/WorkspaceManagementView.js
Labels: manager view

#384 Fix share dialog closing when regenerating link
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/sharing/LinkSharingActions.js
Labels: other ui
