Repository rage/concepts, pull requests merged in 2019-08, with the labels that each got.

#178 Add eslint arrow body style rule
  .eslintrc
  backend/src/errorLogger.js
  frontend/src/apollo/update/concept.js
  frontend/src/apollo/update/conceptLink.js
  frontend/src/apollo/update/course.js
  frontend/src/apollo/update/port.js
  frontend/src/components/common/PrivateRoute.js
  frontend/src/components/course/CourseHeatmap.js
  frontend/src/components/course/GuidedCourseContainer.js
  frontend/src/components/course/GuidedCourseTray.js
  frontend/src/components/course/GuidedCourseView.js
  frontend/src/components/project/CloneView.js
  frontend/src/components/project/ProjectSharingDialog.js
  frontend/src/components/project/UserWorkspaceList.js
  frontend/src/components/resource/Resource.js
  frontend/src/components/resource/ResourceForm.js
  frontend/src/lib/authentication.js
  frontend/src/lib/userProgress.js
Labels: internal

#183 Miscellaneous backend refactoring
  backend/package.json
  backend/src/TMCAuthentication.js
  backend/src/errorLogger.js
  backend/src/middleware/authentication.js
  backend/src/resolvers/Mutation/Authentication.js
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/ConceptLink.js
  backend/src/resolvers/Mutation/CourseLink.js
  backend/src/resolvers/Mutation/Port.js
  backend/src/resolvers/Mutation/Project.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Query/Port.js
  backend/src/resolvers/Type/Concept.js
  backend/src/resolvers/Type/ConceptLink.js
  backend/src/resolvers/Type/Course.js
  backend/src/resolvers/Type/CourseLink.js
  backend/src/resolvers/Type/Project.js
  backend/src/resolvers/Type/ProjectParticipant.js
  backend/src/resolvers/Type/ProjectToken.js
  backend/src/resolvers/Type/Resource.js
  backend/src/resolvers/Type/URL.js
  backend/src/resolvers/Type/User.js
  backend/src/resolvers/Type/Workspace.js
  backend/src/resolvers/Type/WorkspaceParticipant.js
  backend/src/resolvers/Type/WorkspaceToken.js
  backend/src/resolvers/Type/typeutil.js
  backend/src/static/mockWorkspace.json
  backend/src/static/port.schema.json
  backend/yarn.lock
  frontend/src/components/porting/PortView.js
  frontend/src/components/porting/port.schema.json
  frontend/src/static/port.schema.json
Labels: internal

#223 Graph view fixes
  frontend/package.json
  frontend/src/App.js
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/graph/GraphView.js
  frontend/src/views/graph/colors.json
  frontend/src/views/graph/generateColors.js
  frontend/yarn.lock
Labels: internal

#226 Random updates
  backend/schema/generated/prisma-client/index.d.ts
  backend/schema/generated/prisma-client/prisma-schema.js
  backend/src/errorLogger.js
  backend/src/errors.js
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/ConceptLink.js
  backend/src/resolvers/Mutation/Course.js
  backend/src/resolvers/Mutation/CourseLink.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Mutation/WorkspaceSharing.js
  backend/src/resolvers/Query/Concept.js
  backend/src/resolvers/Query/Course.js
  frontend/src/components/NavBar.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/mapper/CourseTray.js
Labels: internal

#230 Improve portview
  frontend/src/views/porting/PortView.js
Labels: port view

#234 Workspace name shown after deselecting project
  frontend/src/views/porting/PortView.js
Labels: port view

#236 Delete legacy graphql stuff
  frontend/src/graphql/ConceptService.js
  frontend/src/graphql/CourseService.js
  frontend/src/graphql/ResourceService.js
Labels: internal

#239 Miscellaneous improvements
  backend/docker-compose.yml
  frontend/src/components/AuthIcon.js
  frontend/src/components/DividerWithText.js
  frontend/src/dialogs/Dialog.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/PrerequisiteContainer.js
  frontend/src/views/porting/PortView.js
  frontend/src/views/project/CloneView.js
  frontend/yarn.lock
Labels: internal

#241 Make dialog lists and bloom tag input less hacky
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/concept/TaxonomyTags.js
  frontend/src/dialogs/concept/useCreateConceptDialog.js
  frontend/src/dialogs/concept/useEditConceptDialog.js
Labels: internal

#245 Make main view have projects and workspaces side by side
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/views/home/ProjectList.js
  frontend/src/views/home/UserViewContent.js
  frontend/src/views/home/WorkspaceList.js
Labels: other ui

#246 Add minor improvements to UI
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/components/NavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/dialogs/Dialog.js
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/home/HomeView.js
  frontend/src/views/home/UserViewContent.js
  frontend/src/views/project/MergeList.js
  frontend/src/views/project/UserWorkspaceList.js
Labels: other ui

#251 Add missing queries to workspaceById
  frontend/src/graphql/Query/Workspace.js
Labels: bug

#258 Update lifecycle method names
  frontend/src/components/LoadingBar.js
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/concept/ConceptLink.js
Labels: internal

#265 Add concept merging
  backend/schema/extra.graphql
  backend/schema/generated/schema.graphql
  backend/src/errors.js
  backend/src/resolvers/Mutation/Merge.js
  frontend/package.json
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/sharing/LinkSharingActions.js
  frontend/src/graphql/Mutation/Concept.js
  frontend/src/graphql/Mutation/Merge.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/MergeDialog.js
  frontend/src/views/manager/WorkspaceManagementView.js
  frontend/yarn.lock
Labels: manager view

#273 Switch to production access control
  backend/src/resolvers/Mutation/Authentication.js
Labels: backend, internal

#277 Move official checkbox next to buttons
  frontend/src/dialogs/Dialog.js
  frontend/src/views/join/JoinView.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
Labels: manager view

#280 Sorting concepts
  frontend/src/views/manager/CourseEditor.js
Labels: manager view

#281 Patch around Apollo client bug preventing joining workspaces
  frontend/src/graphql/Query/Sharing.js
  frontend/src/views/join/JoinView.js
Labels: internal

#282 Indicate what account the user is logged into
  frontend/src/components/AuthIcon.js
  frontend/src/lib/authentication.js
Labels: other ui

#284 Add random default workspace name in clone view
  frontend/src/lib/adjectives.json
  frontend/src/lib/animals.json
  frontend/src/lib/generateName.js
  frontend/src/views/project/CloneView.js
Labels: other ui

#287 Set description to tooltips in manager view
  frontend/src/views/manager/CourseEditor.js
Labels: bug

#288 Fix crash on tag removal and addition
  frontend/src/dialogs/Dialog.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/MergeDialog.js
Labels: bug
