Repository rage/concepts, pull requests merged in 2019-09, with the labels that each got.

#291 Minor tweaks to UI
  backend/docker-compose.yml
  frontend/src/components/AuthIcon.js
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/home/HomeView.js
  frontend/src/views/home/UserViewContent.js
  frontend/src/views/mapper/ActiveCourse.js
Labels: other ui

#294 Improve abstraction in EditableTable
  frontend/src/views/project/manager/EditableTable.js
  frontend/src/views/project/manager/PointGroupsView.js
Labels: internal

#295 Add tag import/export
  .eslintrc
  backend/src/resolvers/Mutation/Port.js
  backend/src/resolvers/Query/Port.js
  backend/src/static/port.schema.json
Labels: backend, port view

#298 ESLint fixes
  .eslintrc
  backend/src/resolvers/Mutation/ConceptLink.js
  backend/src/resolvers/Mutation/PointGroup.js
  backend/src/resolvers/Mutation/Port.js
  frontend/.eslintrc
  frontend/src/apollo/update/project.js
  frontend/src/components/NavBar.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/concept/TaxonomyTags.js
  frontend/src/graphql/Mutation/Course.js
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/home/UserViewContent.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/MergeDialog.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/concept/ConceptLink.js
  frontend/src/views/porting/PortView.js
  frontend/src/views/project/manager/EditableTable.js
  frontend/src/views/project/manager/PointGroupsView.js
Labels: internal

#296 Add member view to projects and workspaces
  backend/schema/extra.graphql
  backend/schema/generated/schema.graphql
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/Course.js
  backend/src/resolvers/Mutation/Sharing.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Mutation/index.js
  backend/src/resolvers/Query/Project.js
  backend/src/resolvers/Query/Sharing.js
  backend/src/resolvers/Query/Workspace.js
  backend/src/resolvers/Query/index.js
  frontend/package.json
  frontend/src/App.js
  frontend/src/apollo/apolloClient.js
  frontend/src/components/EditableTable.js
  frontend/src/components/NavBar.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/graphql/Mutation/Concept.js
  frontend/src/graphql/Mutation/Sharing.js
  frontend/src/graphql/Query/Project.js
  frontend/src/graphql/Query/Workspace.js
  frontend/src/index.js
  frontend/src/lib/authentication.js
  frontend/src/lib/userProgress.js
  frontend/src/views/home/HomeView.js
  frontend/src/views/login/LoginView.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/MembersView.js
  frontend/src/views/project/PointGroupsView.js
  frontend/yarn.lock
Labels: enhancement, other ui

#299 Completion points
  backend/schema/datamodel.prisma
  backend/schema/generated/prisma-client/index.d.ts
  backend/schema/generated/prisma-client/prisma-schema.js
  backend/schema/generated/schema.graphql
  backend/src/index.js
  backend/src/pointsAPI.js
  backend/src/resolvers/Mutation/Concept.js
Labels: enhancement

#303 Course themes
  frontend/src/dialogs/Dialog.js
  frontend/src/dialogs/concept/useCreateConceptDialog.js
  frontend/src/dialogs/concept/useEditConceptDialog.js
  frontend/src/dialogs/course/useCreateCourseDialog.js
  frontend/src/dialogs/course/useEditCourseDialog.js
  frontend/src/dialogs/tagSelectUtils.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/MergeDialog.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/CourseTray.js
Labels: mapper view

#305 Use JSS reference syntax
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/concept/Concept.js
  frontend/src/views/project/ProjectView.js
Labels: internal

#304 Fix updating concept link target element after changing course links
  frontend/src/graphql/Query/Course.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/concept/ConceptLink.js
Labels: mapper view

#306 Remove IDs from elements
  frontend/src/apollo/apolloClient.js
  frontend/src/components/InfoSnackbar.js
  frontend/src/components/NavBar.js
  frontend/src/views/login/LoginView.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/redirect/CreateCourseForm.js
  frontend/src/views/porting/PortView.js
  frontend/src/views/project/CloneView.js
Labels: internal

#307 Minor refactoring and warning for small screens
  frontend/src/App.js
  frontend/src/WindowTooSmall.js
  frontend/src/Wrapper.js
  frontend/src/index.js
  frontend/src/store.js
Labels: other ui

#308 Move official-by-default into client
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/Course.js
  backend/src/resolvers/Mutation/Workspace.js
  frontend/src/apollo/apolloClient.js
  frontend/src/graphql/Query/Workspace.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/manager/MergeDialog.js
  frontend/src/views/manager/WorkspaceManagementView.js
  frontend/src/views/mapper/ActiveCourse.js
Labels: internal, manager view

#313 Add docker stuff for production deployment
  .dockerignore
  Dockerfile
  backend/docker-compose.yml
  backend/src/index.js
  docker-compose.yml
Labels: backend

#315 Add docker stuff for development
  backend/Dockerfile.dev
  backend/docker-compose.yml
  compose
  development.yml
  docker-compose.yml
  frontend/Dockerfile.dev
  frontend/src/setupProxy.js
  prisma
  production.yml
Labels: backend, internal

#316 Remove courses
  backend/.dockerignore
  backend/schema/datamodel.prisma
  backend/schema/generated/prisma-client/index.d.ts
  backend/schema/generated/prisma-client/prisma-schema.js
  backend/schema/generated/schema.graphql
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/Merge.js
  backend/src/resolvers/Mutation/Port.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Type/Concept.js
  frontend/.dockerignore
  frontend/src/apollo/update/concept.js
  frontend/src/components/FocusOverlay.js
  frontend/src/components/LoadingBar.js
  frontend/src/dialogs/DialogProvider.js
  frontend/src/dialogs/sharing/useShareDialog.js
  frontend/src/graphql/Mutation/Concept.js
  frontend/src/graphql/Mutation/Course.js
  frontend/src/graphql/Mutation/CourseLink.js
  frontend/src/graphql/Mutation/Merge.js
  frontend/src/graphql/Query/Course.js
  frontend/src/graphql/Query/Workspace.js
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/PrerequisiteContainer.js
  frontend/src/views/mapper/concept/ConceptLink.js
Labels: internal

#320 Add role to auth menu
  frontend/src/components/AuthIcon.js
Labels: other ui

#321 Add dev proxy for prisma admin and don't expose prisma port
  development.yml
  docker-compose.yml
  frontend/src/setupProxy.js
Labels: internal

#325 Add concept grouping
  frontend/package.json
  frontend/src/views/manager/ConceptGroup.js
  frontend/src/views/manager/CourseEditor.js
  frontend/yarn.lock
Labels: manager view

#323 Rework user guide
  frontend/public/guide/create-workspace.webm
  frontend/public/guide/entering-course-mapper.webm
  frontend/public/guide/manager/delete-concept.webm
  frontend/public/guide/manager/delete-course.webm
  frontend/public/guide/manager/edit-concept.webm
  frontend/public/guide/manager/edit-course.webm
  frontend/public/guide/manager/new-concept.webm
  frontend/public/guide/manager/new-course.webm
  frontend/public/guide/mapper/add-course-as-prereq.webm
  frontend/public/guide/mapper/draw-link.webm
  frontend/public/guide/mapper/focus-concept-delete-link.webm
  frontend/public/guide/mapper/new-concept-active-course.webm
  frontend/public/guide/mapper/new-concept-prereq-course.webm
  frontend/public/guide/mapper/new-course.webm
  frontend/public/guide/mapper/open-course-tray.webm
  frontend/src/App.js
  frontend/src/Wrapper.js
  frontend/src/components/AuthIcon.js
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/components/FocusOverlay.js
  frontend/src/components/InfoBox.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/dialogs/DialogProvider.js
  frontend/src/index.css
  frontend/src/static/userGuide.json
  frontend/src/useRouter.js
  frontend/src/views/graph/CytoGraphView.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/home/HomeView.js
  frontend/src/views/home/ProjectList.js
  frontend/src/views/join/JoinView.js
  frontend/src/views/login/LoginView.js
  frontend/src/views/manager/WorkspaceManagementView.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/PrerequisiteContainer.js
  frontend/src/views/mapper/concept/Concept.js
  frontend/src/views/mapper/redirect/CreateCourseForm.js
  frontend/src/views/members/MembersView.js
  frontend/src/views/project/CloneView.js
Labels: other ui

#330 User guide for manager
  frontend/public/guide/manager/delete-concept.webm
  frontend/public/guide/manager/delete-course.webm
  frontend/public/guide/manager/edit-concept.webm
  frontend/public/guide/manager/edit-course.webm
  frontend/src/components/FocusOverlay.js
  frontend/src/components/InfoBox.js
  frontend/src/static/userGuide.json
  frontend/src/static/userGuide.schema.json
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
Labels: user guide

#329 Add user guide to user home page
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/static/userGuide.json
  frontend/src/views/home/ProjectList.js
  frontend/src/views/home/UserViewContent.js
Labels: user guide

#331 Share permission data structures with frontend and backend
  .eslintrc
  Dockerfile
  backend/.babelrc
  backend/.eslintrc
  backend/.gitignore
  backend/package.json
  backend/src/accessControl.js
  backend/src/middleware/authentication.js
  backend/src/permissions.js
  backend/src/resolvers/Mutation/Authentication.js
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/Merge.js
  backend/src/resolvers/Mutation/Port.js
  backend/src/resolvers/Mutation/Project.js
  backend/src/resolvers/Mutation/Sharing.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Query/Sharing.js
  backend/yarn.lock
  development.yml
  frontend/.babelrc
  frontend/.eslintrc
  frontend/config-overrides.js
  frontend/package.json
  frontend/src/apollo/update/port.js
  frontend/src/components/AuthIcon.js
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/components/LoadingBar.js
  frontend/src/components/NavBar.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/dialogs/sharing/useShareDialog.js
  frontend/src/lib/permissions.js
  frontend/src/lib/userProgress.js
  frontend/src/store.js
  frontend/src/views/heatmap/HeatmapView.js
  frontend/src/views/home/HomeView.js
  frontend/src/views/home/UserViewContent.js
  frontend/src/views/join/JoinView.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseTray.js
  frontend/src/views/mapper/concept/Concept.js
  frontend/src/views/members/MembersView.js
  frontend/src/views/porting/PortView.js
  frontend/src/views/project/CloneView.js
  frontend/src/views/project/ProjectView.js
  frontend/src/views/project/UserWorkspaceList.js
  frontend/yarn.lock
Labels: internal

#333 Miscellaneous cleanup
  backend/.eslintignore
  backend/src/middleware/authentication.js
  backend/src/pointsAPI.js
  backend/src/resolvers/Mutation/Authentication.js
  backend/src/resolvers/Mutation/Concept.js
  backend/src/resolvers/Mutation/PointGroup.js
  backend/src/resolvers/Mutation/Port.js
  backend/src/resolvers/Mutation/Project.js
  backend/src/resolvers/Mutation/Workspace.js
  backend/src/resolvers/Query/Workspace.js
  backend/src/resolvers/Type/Project.js
  backend/src/resolvers/Type/typeutil.js
  frontend/.eslintrc
  frontend/package.json
  frontend/src/apollo/update/project.js
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/components/NavBar.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/components/WorkspaceNavBar.js
  frontend/src/dialogs/DialogProvider.js
  frontend/src/dialogs/tagSelectUtils.js
  frontend/src/dialogs/workspace/WorkspaceCreationActions.js
  frontend/src/graphql/Mutation/Authentication.js
  frontend/src/graphql/Mutation/Sharing.js
  frontend/src/graphql/Mutation/User.js
  frontend/src/graphql/Mutation/index.js
  frontend/src/graphql/Query/Sharing.js
  frontend/src/graphql/Query/User.js
  frontend/src/graphql/Query/index.js
  frontend/src/lib/authentication.js
  frontend/src/lib/errorParse.js
  frontend/src/views/error/NotFoundView.js
  frontend/src/views/porting/PortView.js
  frontend/yarn.lock
Labels: internal

#334 Briefly highlight concept link after creating even if not focused
  frontend/src/views/mapper/ActiveCourse.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/CourseMapperView.js
  frontend/src/views/mapper/PrerequisiteContainer.js
  frontend/src/views/mapper/concept/Concept.js
  frontend/src/views/mapper/concept/ConceptLink.js
Labels: enhancement, mapper view

#335 Add staff-only parts to user guide
  frontend/src/components/BaseWorkspaceList.js
  frontend/src/components/FocusOverlay.js
  frontend/src/components/InfoBox.js
  frontend/src/components/ProjectNavBar.js
  frontend/src/static/userGuide.json
  frontend/src/static/userGuide.schema.json
  frontend/src/views/home/UserViewContent.js
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
  frontend/src/views/mapper/Course.js
  frontend/src/views/mapper/PrerequisiteContainer.js
  frontend/src/views/project/MergeList.js
  frontend/src/views/project/ProjectView.js
  frontend/src/views/project/UserWorkspaceList.js
Labels: user guide

#342 Fix editing courses and concepts in mapper
  frontend/src/views/manager/CourseEditor.js
  frontend/src/views/manager/CourseList.js
Labels: bug, mapper view
